/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;  
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Login_Application extends javax.swing.JFrame {

    /**
     * Creates new form Login_Application
     */
    public Login_Application() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTUser = new javax.swing.JTextField();
        JPassword = new javax.swing.JTextField();
        BLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText("Account");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 300, 90, 20));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 120, 20));

        JTUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JTUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTUserActionPerformed(evt);
            }
        });
        getContentPane().add(JTUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 330, 320, 40));

        JPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(JPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 430, 320, 40));

        BLogin.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        BLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_app/images/login.png"))); // NOI18N
        BLogin.setText("Login");
        BLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLoginActionPerformed(evt);
            }
        });
        getContentPane().add(BLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 510, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/spist2-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 980, 360));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Removal-211.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("ACCESS ATTENDANCE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 270, -1));

        BExit.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        BExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_app/images/close.png"))); // NOI18N
        BExit.setText("EXIT");
        BExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExitActionPerformed(evt);
            }
        });
        getContentPane().add(BExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 510, 140, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/backg (1).jpg"))); // NOI18N
        jLabel2.setText("`");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1380, 790));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JTUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTUserActionPerformed

    private void JPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPasswordActionPerformed

    private void BLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLoginActionPerformed
      if (JTUser.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Please fill out Username ");    
      }else if (JPassword.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Please fill out Password ");   
      }else if (JTUser.getText().contains("c23-4874-01") && JPassword.getText().contains("12345")){
          Attendance_list AList = new Attendance_list();
          AList.show();
          dispose();
          JOptionPane.showMessageDialog(null, "Welcome Sir/Maam ");
      }else if (JTUser.getText().contains("Salamander") && JPassword.getText().contains("54321")){
          easterD D_bug = new easterD();
          D_bug.show();
      } else JOptionPane.showMessageDialog(null, "ERRPR 101 "); 
    }//GEN-LAST:event_BLoginActionPerformed

    private void BExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExitActionPerformed
      dispose();
    }//GEN-LAST:event_BExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Application().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BExit;
    private javax.swing.JButton BLogin;
    private javax.swing.JTextField JPassword;
    private javax.swing.JTextField JTUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
